from pathlib import Path

OUTPUT_DIR = Path("generated")
OUTPUT_DIR.mkdir(exist_ok=True)

svg = """<svg xmlns="http://www.w3.org/2000/svg" width="400" height="120">
  <rect width="100%" height="100%" fill="#0d1117"/>
  <text x="20" y="50" fill="white" font-size="24">
    Hello, GitHub!
  </text>
  <text x="20" y="90" fill="#8b949e" font-size="16">
    This SVG was generated by Python.
  </text>
</svg>
"""

(OUTPUT_DIR / "test.svg").write_text(svg, encoding="utf-8")

print("✓ Generated generated/test.svg")